### PR TITLE
Allow handling of incoming emails via Mandrill API

### PR DESCRIPTION
**Pull request by julianlam**
This one's the right commit :smile: 

Let me know if you run into trouble setting it up to test.

### CODE REVIEW

**Comment by akhoury** [comment]
is this backward compatible, settings wise? meaning should I patch, minor or major release?

**Comment by julianlam** [comment]
Yep! It's backwards compatible since all of the added settings are new.

**Comment by julianlam** [comment]
Fixe a bug that caused it to not work :shipit:

**Comment by akhoury** [comment]
ok cool, I will merge this week

**Pull request merged**
